### ISSUE TITLE
Se agregan objetos en el medio

### ISSUE THREAD

**Issue by emitolaba95** [emitolaba95/2017_1C_3051_WOLFHOUND#1]
Cuando agregamos un objeto nuevo después de editarlo, al querer cargarlo desde el código, se agrega en el medio de la escena. Y asi pasa a medida que agregamos nuevos objetos. Por ahora lo solucioné haciendo un remove de la lista de meshes de la escena, pero no me parece la mejor solución

**Comment by SLDG1297** [comment]
Uh. Tendría que haber hecho el issue antes de pullear XD Ahí se me ocurrió hacer un removeAll de todos los objetos que aparecen en el centro del mapa (Asumiendo que la coordenada del centro es <0,0,0>). Fijense.

**Comment by emitolaba95** [comment]
Ah buenisimo! Es mucho mejor que andar buscando por el nombre y borrar uno por uno. Mientras no agreguemos objetos nuevos en el centro esta bien por ahora.

**Comment by SLDG1297** [comment]
Ok. La verdad que no sé por qué pasa eso. Será problema del editor? Habría que consultarlo con los profes.
